package exception;

import java.util.InputMismatchException;
import java.util.Scanner;

public class Step09_multiException {
	
	/*
	 * 다중 catch 문
	 *  - 하나의 try 블럭에서 발생하는 예외를
	 *    다중 catch 블럭으로 예외를 처리할 수 있다.
	 *  - 다수의 예외가 발생되는 경우 해당된다.
	 *  - Exception클래스는 모든 예외를 처리한다.
	 *    -> 반드시 마지막 catch 블럭에서 사용
	 */
	public static void main(String[] args) {
		// 
		Scanner sc = new Scanner(System.in);
		String str = "a";
		int num;
		int []score = new int[3];
		score[2] = 10;
		try{
			System.out.println("정수 입력 :");
			num = sc.nextInt(); //타입 불일치 예외
			int result = 10/2; //산술적 예외
			System.out.println("str 길이 : "+str.length()); //널포인트 예외
			System.out.println(score[3]=100); // index초과 예외
		}catch(InputMismatchException e1){
			System.out.println("정수만 입력하세요.");
		}catch(ArithmeticException e2){
			System.out.println("산술적 예외 발생");
		}catch(NullPointerException e3){
			System.out.println("널포인트 예외");
		}catch(Exception e4){
			System.out.println("나도 모르는 예외:"+e4);
		}
 	}

}
